name: Deploy Worker
on:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "latest"
        cache: "npm"

    - name: Install modules
      run: npm i wrangler@latest

    - name: Build
      run: npx wrangler deploy --dry-run --outdir=dist

    - name: Add Header
      run: |
        cp ${{ github.workspace }}/dist/worker.js ${{ github.workspace }}/dist/worker-original.js \
        && echo -e \
        "/*!
          * v2ray Subscription Worker (${{ github.sha }})
          * Copyright 2024 Vahid Farid (https://twitter.com/vahidfarid)
          * Licensed under GPLv3 (https://github.com/vfarid/v2ray-worker/blob/main/Licence.md)
          */

        $(cat ${{ github.workspace }}/dist/worker.js)" > ${{ github.workspace }}/dist/worker.js

    - name: Deploy
      run: |
        sed -i "s/V2RAY_WORKER_KV_ID/${{ secrets.V2RAY_WORKER_KV_ID }}/g" wrangler.toml \
        && npx wrangler deploy
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
